txt = open('/app/frontend/pages/settings.tsx').read()
txt = txt.replace('<main className="flex-1 p-8">', '<main className="flex-1 p-4 md:p-8 pb-24 md:pb-8">')
txt = txt.replace('className="grid grid-cols-2 gap-4', 'className="grid grid-cols-1 md:grid-cols-2 gap-4')
open('/app/frontend/pages/settings.tsx', 'w').write(txt)
print('done')
