import os
os.makedirs('/app/frontend', exist_ok=True)
txt = '''
window.printGivingStatement = function(memberName, records, total) {
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Giving Statement - ${memberName}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #4338ca; padding-bottom: 20px; }
        .header h1 { color: #4338ca; margin: 0; font-size: 24px; }
        .header p { color: #666; margin: 5px 0; }
        .member-info { background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background: #4338ca; color: white; padding: 10px; text-align: left; font-size: 12px; }
        td { padding: 10px; border-bottom: 1px solid #eee; font-size: 13px; }
        tr:nth-child(even) { background: #f8f9fa; }
        .total-row { background: #e8f5e9 !important; font-weight: bold; }
        .footer { text-align: center; margin-top: 30px; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 15px; }
        .badge { background: #e0e7ff; color: #4338ca; padding: 2px 8px; border-radius: 10px; font-size: 11px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>ChurchHub</h1>
        <p>Grace Community Church — Nairobi, Kenya</p>
        <h2 style="margin-top:15px;">Giving Statement</h2>
      </div>
      <div class="member-info">
        <strong>Member:</strong> ${memberName}<br/>
        <strong>Generated:</strong> ${new Date().toLocaleDateString('en-KE', {year:'numeric',month:'long',day:'numeric'})}<br/>
        <strong>Period:</strong> All time
      </div>
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Category</th>
            <th>Amount (KES)</th>
            <th>Method</th>
            <th>M-Pesa Ref</th>
          </tr>
        </thead>
        <tbody>
          ${records.map(r => `
            <tr>
              <td>${r.created_at ? r.created_at.slice(0,10) : '-'}</td>
              <td><span class="badge">${r.category_name || '-'}</span></td>
              <td style="font-weight:bold;color:#16a34a;">KES ${r.amount_kes.toLocaleString()}</td>
              <td style="text-transform:capitalize;">${r.payment_method || '-'}</td>
              <td>${r.mpesa_ref || '-'}</td>
            </tr>
          `).join('')}
          <tr class="total-row">
            <td colspan="2"><strong>TOTAL GIVING</strong></td>
            <td colspan="3"><strong style="color:#16a34a;">KES ${total.toLocaleString()}</strong></td>
          </tr>
        </tbody>
      </table>
      <div class="footer">
        This is an official giving statement from Grace Community Church.<br/>
        Generated by ChurchHub — Manage your church, your way.
      </div>
    </body>
    </html>
  `;
  const win = window.open('', '_blank');
  win.document.write(html);
  win.document.close();
  win.print();
};
'''
open('/app/frontend/print_utils.js', 'w').write(txt)
print('done')
