"use client";
import { useEffect, useState } from "react";
import Sidebar from "../../../components/Sidebar";
import api from "../../../lib/api";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, DollarSign, Printer } from "lucide-react";

export default function MemberDetailPage() {
  const params = useParams();
  const id = params.id;
  const [member, setMember] = useState<any>(null);
  const [giving, setGiving] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) return;
    Promise.all([
      api.get("/members/" + id),
      api.get("/members/" + id + "/giving")
    ]).then(([mr, gr]) => {
      setMember(mr.data);
      setGiving(gr.data);
    }).finally(() => setLoading(false));
  }, [id]);

  const total = giving.reduce((s, r) => s + r.amount_kes, 0);

  const printStatement = () => {
    if (!member) return;
    const memberName = member.first_name + " " + member.last_name;
    const html = `<!DOCTYPE html><html><head><title>Giving Statement - ${memberName}</title>
    <style>
      body{font-family:Arial,sans-serif;padding:40px;color:#333;}
      .header{text-align:center;margin-bottom:30px;border-bottom:2px solid #4338ca;padding-bottom:20px;}
      .header h1{color:#4338ca;margin:0;font-size:24px;}
      table{width:100%;border-collapse:collapse;margin-bottom:20px;}
      th{background:#4338ca;color:white;padding:10px;text-align:left;font-size:12px;}
      td{padding:10px;border-bottom:1px solid #eee;font-size:13px;}
      tr:nth-child(even){background:#f8f9fa;}
      .total-row{background:#e8f5e9!important;font-weight:bold;}
      .footer{text-align:center;margin-top:30px;font-size:11px;color:#999;border-top:1px solid #eee;padding-top:15px;}
    </style></head><body>
    <div class="header"><h1>ChurchHub</h1><p>Grace Community Church — Nairobi, Kenya</p><h2>Giving Statement</h2></div>
    <p><strong>Member:</strong> ${memberName} &nbsp; <strong>Phone:</strong> ${member.phone || "-"}</p>
    <p><strong>Generated:</strong> ${new Date().toLocaleDateString("en-KE",{year:"numeric",month:"long",day:"numeric"})}</p>
    <table><thead><tr><th>Date</th><th>Category</th><th>Amount (KES)</th><th>Method</th><th>M-Pesa Ref</th></tr></thead>
    <tbody>${giving.map(r => `<tr><td>${r.created_at?r.created_at.slice(0,10):"-"}</td><td>${r.category_name||"-"}</td><td style="font-weight:bold;color:#16a34a;">KES ${r.amount_kes.toLocaleString()}</td><td>${r.payment_method||"-"}</td><td>${r.mpesa_ref||"-"}</td></tr>`).join("")}
    <tr class="total-row"><td colspan="2"><strong>TOTAL</strong></td><td colspan="3"><strong style="color:#16a34a;">KES ${total.toLocaleString()}</strong></td></tr>
    </tbody></table>
    <div class="footer">Official giving statement from Grace Community Church.<br/>Generated by ChurchHub</div>
    </body></html>`;
    const win = window.open("", "_blank");
    win.document.write(html);
    win.document.close();
    win.print();
  };

  if (loading) return <div className="flex min-h-screen bg-gray-50"><Sidebar /><main className="flex-1 p-8 text-gray-400">Loading...</main></div>;
  if (!member) return <div className="flex min-h-screen bg-gray-50"><Sidebar /><main className="flex-1 p-8 text-gray-400">Member not found.</main></div>;

  return (
    <div className="flex min-h-screen bg-gray-50">
      <Sidebar />
      <main className="flex-1 p-8">
        <div className="flex items-center gap-2 mb-4">
          <Link href="/members" className="flex items-center gap-1 text-indigo-500 text-sm hover:underline">
            <ArrowLeft className="w-4 h-4" /> Back to Members
          </Link>
        </div>
        <div className="bg-white rounded-xl shadow-sm p-6 mb-6">
          <div className="flex items-start justify-between">
            <div>
              <h1 className="text-2xl font-bold text-gray-800">{member.first_name} {member.last_name}</h1>
              <p className="text-gray-500 text-sm mt-1">{member.phone || "No phone"} · {member.email || "No email"}</p>
            </div>
            <span className="text-xs bg-green-100 text-green-700 px-3 py-1 rounded-full font-medium capitalize">{member.membership_status}</span>
          </div>
          <div className="grid grid-cols-4 gap-4 mt-6">
            <div><p className="text-xs text-gray-400">Gender</p><p className="text-sm font-medium text-gray-700 capitalize">{member.gender || "—"}</p></div>
            <div><p className="text-xs text-gray-400">Marital Status</p><p className="text-sm font-medium text-gray-700 capitalize">{member.marital_status || "—"}</p></div>
            <div><p className="text-xs text-gray-400">Occupation</p><p className="text-sm font-medium text-gray-700">{member.occupation || "—"}</p></div>
            <div><p className="text-xs text-gray-400">Member Since</p><p className="text-sm font-medium text-gray-700">{member.membership_date || "—"}</p></div>
          </div>
        </div>
        <div className="bg-white rounded-xl shadow-sm p-6 mb-4">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h2 className="text-lg font-semibold text-gray-800">Giving History</h2>
              <p className="text-xs text-gray-400">Total: <span className="font-bold text-green-600">KES {total.toLocaleString()}</span></p>
            </div>
            <button onClick={printStatement} className="flex items-center gap-2 border border-indigo-200 text-indigo-600 px-4 py-2 rounded-lg text-sm hover:bg-indigo-50">
              <Printer className="w-4 h-4" /> Print Giving Statement
            </button>
          </div>
          {giving.length === 0 ? (
            <div className="text-center py-8">
              <DollarSign className="w-8 h-8 text-gray-300 mx-auto mb-2" />
              <p className="text-gray-400 text-sm">No giving records yet</p>
              <Link href="/giving" className="text-indigo-600 text-sm hover:underline mt-1 block">+ Record Giving</Link>
            </div>
          ) : (
            <table className="w-full">
              <thead className="bg-gray-50 border-b border-gray-100">
                <tr>{["Date","Category","Amount (KES)","Method","M-Pesa Ref"].map(h => (
                  <th key={h} className="text-left text-xs text-gray-500 font-medium px-4 py-2">{h}</th>
                ))}</tr>
              </thead>
              <tbody>
                {giving.map(r => (
                  <tr key={r.id} className="border-b border-gray-50 hover:bg-gray-50">
                    <td className="px-4 py-3 text-sm text-gray-500">{r.created_at?.slice(0,10)}</td>
                    <td className="px-4 py-3"><span className="text-xs bg-indigo-100 text-indigo-700 px-2 py-0.5 rounded-full">{r.category_name}</span></td>
                    <td className="px-4 py-3 text-sm font-bold text-green-600">KES {r.amount_kes.toLocaleString()}</td>
                    <td className="px-4 py-3 text-sm text-gray-500 capitalize">{r.payment_method}</td>
                    <td className="px-4 py-3 text-sm text-gray-500">{r.mpesa_ref || "—"}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
        <div className="flex gap-3">
          <Link href="/giving" className="bg-indigo-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-indigo-700">+ Record Giving for this Member</Link>
          <Link href="/attendance" className="border border-gray-200 text-gray-600 px-4 py-2 rounded-lg text-sm hover:bg-gray-50">View Attendance</Link>
        </div>
      </main>
    </div>
  );
}
