"use client";
import { useEffect, useState } from "react";
import Sidebar from "../../../components/Sidebar";
import api from "../../../lib/api";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, DollarSign, Printer, ChevronRight, CalendarCheck, Download } from "lucide-react";

export default function MemberDetailPage() {
  const params = useParams();
  const id = params.id;
  const [member, setMember]   = useState<any>(null);
  const [giving, setGiving]   = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo]     = useState('');

  useEffect(() => {
    if (!id) return;
    Promise.all([
      api.get("/members/" + id),
      api.get("/members/" + id + "/giving")
    ]).then(([mr, gr]) => {
      setMember(mr.data);
      setGiving(gr.data);
    }).finally(() => setLoading(false));
  }, [id]);

  const filteredGiving = giving.filter((r: any) => {
    const d = r.created_at?.slice(0,10) || ''
    if (dateFrom && d < dateFrom) return false
    if (dateTo   && d > dateTo)   return false
    return true
  })

  const total = filteredGiving.reduce((s: number, r: any) => s + r.amount_kes, 0);

  const printStatement = () => {
    if (!member) return;
    const memberName = member.first_name + " " + member.last_name;
    const periodLabel = dateFrom || dateTo
      ? `Period: ${dateFrom || 'All'} to ${dateTo || 'All'}`
      : 'All-time giving statement'
    const html = `<!DOCTYPE html><html><head><title>Giving Statement - ${memberName}</title>
    <style>
      body{font-family:Arial,sans-serif;padding:40px;color:#333}
      .header{text-align:center;margin-bottom:30px;border-bottom:3px solid #4338ca;padding-bottom:20px}
      .header h1{color:#4338ca;margin:0 0 4px;font-size:26px;font-weight:900}
      .header .subtitle{color:#6366f1;font-size:14px;margin:0}
      .meta{margin-bottom:20px;font-size:13px;color:#555}
      .meta strong{color:#333}
      .period{background:#f0f0ff;border:1px solid #c7d2fe;border-radius:8px;padding:8px 14px;
               display:inline-block;font-size:12px;color:#4338ca;font-weight:600;margin-bottom:16px}
      table{width:100%;border-collapse:collapse;margin-bottom:20px}
      th{background:#4338ca;color:white;padding:10px 12px;text-align:left;font-size:12px}
      td{padding:10px 12px;border-bottom:1px solid #eee;font-size:13px}
      tr:nth-child(even){background:#f8f9fa}
      .total-row{background:#e8f5e9!important;font-weight:bold}
      .amount{font-weight:bold;color:#16a34a}
      .footer{text-align:center;margin-top:30px;font-size:11px;color:#999;
              border-top:1px solid #eee;padding-top:15px}
    </style></head><body>
    <div class="header">
      <h1>ChurchHub</h1>
      <p class="subtitle">Grace Community Church &mdash; Nairobi, Kenya</p>
      <h2 style="margin:12px 0 0;font-size:18px;color:#333">Official Giving Statement</h2>
    </div>
    <div class="meta">
      <p><strong>Member:</strong> ${memberName} &nbsp;&nbsp;
         <strong>Phone:</strong> ${member.phone || '—'} &nbsp;&nbsp;
         <strong>Email:</strong> ${member.email || '—'}</p>
      <p><strong>Status:</strong> ${member.membership_status} &nbsp;&nbsp;
         <strong>Generated:</strong> ${new Date().toLocaleDateString('en-KE',{year:'numeric',month:'long',day:'numeric'})}</p>
    </div>
    <div class="period">${periodLabel}</div>
    <table>
      <thead><tr>
        <th>Date</th><th>Category</th><th>Amount (KES)</th><th>Method</th><th>M-Pesa Ref</th>
      </tr></thead>
      <tbody>
        ${filteredGiving.map((r: any) => `<tr>
          <td>${r.created_at?.slice(0,10)||'—'}</td>
          <td>${r.category_name||'—'}</td>
          <td class="amount">KES ${r.amount_kes.toLocaleString()}</td>
          <td style="text-transform:capitalize">${r.payment_method||'—'}</td>
          <td>${r.mpesa_ref||'—'}</td>
        </tr>`).join('')}
        <tr class="total-row">
          <td colspan="2"><strong>GRAND TOTAL</strong></td>
          <td colspan="3"><strong class="amount">KES ${total.toLocaleString()}</strong></td>
        </tr>
      </tbody>
    </table>
    <div class="footer">
      This is an official giving statement from Grace Community Church.<br/>
      Generated by ChurchHub &mdash; ${new Date().toLocaleString()}
    </div>
    </body></html>`;
    const win: Window | null = window.open("", "_blank");
    if (!win) return;
    win.document.write(html);
    win.document.close();
    win.print();
  };

  if (loading) return (
    <div className="flex min-h-screen bg-gray-50">
      <Sidebar />
      <main className="flex-1 p-8 flex items-center justify-center">
        <div className="w-8 h-8 border-2 border-indigo-200 border-t-indigo-600 rounded-full animate-spin" />
      </main>
    </div>
  );
  if (!member) return (
    <div className="flex min-h-screen bg-gray-50">
      <Sidebar />
      <main className="flex-1 p-8 text-gray-400">Member not found.</main>
    </div>
  );

  return (
    <div className="flex min-h-screen bg-gray-50">
      <Sidebar />
      <main className="flex-1 min-w-0 pb-24 md:pb-0">

        <header className="sticky top-0 z-30 bg-white/90 backdrop-blur-md border-b border-gray-200
                           px-4 md:px-8 py-3.5 shadow-sm">
          <div className="ml-12 md:ml-0">
            <div className="flex items-center gap-2 text-xs text-gray-400 mb-0.5">
              <Link href="/" className="hover:text-indigo-600 transition-colors">Dashboard</Link>
              <ChevronRight className="w-3 h-3" />
              <Link href="/members" className="hover:text-indigo-600 transition-colors">Members</Link>
              <ChevronRight className="w-3 h-3" />
              <span className="text-gray-600 font-medium">{member.first_name} {member.last_name}</span>
            </div>
            <h1 className="text-gray-900 font-bold text-lg leading-tight">
              {member.first_name} {member.last_name}
            </h1>
          </div>
        </header>

        <div className="p-4 md:p-8 max-w-4xl mx-auto space-y-5">

          <Link href="/members"
            className="inline-flex items-center gap-1.5 text-indigo-600 text-sm font-medium
                       hover:text-indigo-800 transition-colors">
            <ArrowLeft className="w-4 h-4" /> Back to Members
          </Link>

          {/* Member profile card */}
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
            <div className="flex items-start justify-between flex-wrap gap-3">
              <div className="flex items-center gap-4">
                <div className="w-14 h-14 rounded-2xl bg-indigo-100 flex items-center justify-center
                                text-xl font-black text-indigo-600">
                  {member.first_name?.[0]}{member.last_name?.[0]}
                </div>
                <div>
                  <h2 className="text-xl font-bold text-gray-800">{member.first_name} {member.last_name}</h2>
                  <p className="text-gray-500 text-sm mt-0.5">
                    {member.phone || 'No phone'} {member.email ? '· ' + member.email : ''}
                  </p>
                </div>
              </div>
              <span className="text-xs bg-emerald-100 text-emerald-700 px-3 py-1.5 rounded-full
                               font-semibold capitalize border border-emerald-200">
                {member.membership_status}
              </span>
            </div>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-6 pt-5 border-t border-gray-100">
              {[
                { label: 'Gender',         value: member.gender },
                { label: 'Marital Status', value: member.marital_status },
                { label: 'Occupation',     value: member.occupation },
                { label: 'Member Since',   value: member.membership_date },
              ].map(({ label, value }) => (
                <div key={label}>
                  <p className="text-xs text-gray-400 font-medium mb-1">{label}</p>
                  <p className="text-sm font-semibold text-gray-700 capitalize">{value || '—'}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Giving history card */}
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
            <div className="flex items-start justify-between flex-wrap gap-3 mb-5">
              <div>
                <h2 className="text-base font-bold text-gray-800">Giving History</h2>
                <p className="text-xs text-gray-400 mt-0.5">
                  Total: <span className="font-bold text-emerald-600">KES {total.toLocaleString()}</span>
                  {filteredGiving.length !== giving.length &&
                    <span className="ml-1">({filteredGiving.length} of {giving.length} records)</span>}
                </p>
              </div>
              <button onClick={printStatement}
                className="flex items-center gap-2 border border-indigo-200 text-indigo-600
                           px-4 py-2 rounded-xl text-sm font-semibold hover:bg-indigo-50 transition-colors">
                <Printer className="w-4 h-4" /> Print Statement
              </button>
            </div>

            {/* Date range filter */}
            <div className="flex items-center gap-3 mb-4 flex-wrap">
              <div className="flex items-center gap-2 bg-gray-50 border border-gray-200 rounded-xl px-3 py-2">
                <span className="text-xs text-gray-500 font-medium">From</span>
                <input type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)}
                  className="text-sm text-gray-700 bg-transparent focus:outline-none" />
              </div>
              <div className="flex items-center gap-2 bg-gray-50 border border-gray-200 rounded-xl px-3 py-2">
                <span className="text-xs text-gray-500 font-medium">To</span>
                <input type="date" value={dateTo} onChange={e => setDateTo(e.target.value)}
                  className="text-sm text-gray-700 bg-transparent focus:outline-none" />
              </div>
              {(dateFrom || dateTo) && (
                <button onClick={() => { setDateFrom(''); setDateTo('') }}
                  className="text-xs text-indigo-600 font-medium hover:text-indigo-800">
                  Clear filter
                </button>
              )}
            </div>

            {filteredGiving.length === 0 ? (
              <div className="text-center py-10">
                <DollarSign className="w-8 h-8 text-gray-200 mx-auto mb-2" />
                <p className="text-gray-400 text-sm">No giving records{(dateFrom||dateTo) ? ' in this period' : ' yet'}</p>
                <Link href="/giving" className="text-indigo-600 text-sm font-semibold hover:text-indigo-800 mt-2 block">
                  + Record Giving
                </Link>
              </div>
            ) : (
              <div className="overflow-x-auto rounded-xl border border-gray-100">
                <table className="w-full">
                  <thead className="bg-gray-50 border-b border-gray-100">
                    <tr>{['Date','Category','Amount (KES)','Method','M-Pesa Ref'].map((h: string) => (
                      <th key={h} className="text-left text-xs text-gray-500 font-semibold px-4 py-3">{h}</th>
                    ))}</tr>
                  </thead>
                  <tbody>
                    {filteredGiving.map((r: any) => (
                      <tr key={r.id} className="border-b border-gray-50 hover:bg-gray-50 transition-colors">
                        <td className="px-4 py-3 text-sm text-gray-500">{r.created_at?.slice(0,10)}</td>
                        <td className="px-4 py-3">
                          <span className="text-xs bg-indigo-100 text-indigo-700 px-2.5 py-1 rounded-full font-medium">
                            {r.category_name}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-sm font-bold text-emerald-600">
                          KES {r.amount_kes.toLocaleString()}
                        </td>
                        <td className="px-4 py-3 text-sm text-gray-500 capitalize">{r.payment_method}</td>
                        <td className="px-4 py-3 text-sm text-gray-400">{r.mpesa_ref || '—'}</td>
                      </tr>
                    ))}
                  </tbody>
                  <tfoot className="bg-gray-50 border-t-2 border-gray-200">
                    <tr>
                      <td colSpan={2} className="px-4 py-3 text-sm font-bold text-gray-700">TOTAL</td>
                      <td colSpan={3} className="px-4 py-3 text-sm font-black text-emerald-600">
                        KES {total.toLocaleString()}
                      </td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            )}
          </div>

          {/* Next Step buttons */}
          <div className="flex gap-3 flex-wrap">
            <Link href="/giving"
              className="flex items-center gap-2 bg-indigo-600 text-white px-5 py-2.5 rounded-xl
                         text-sm font-semibold hover:bg-indigo-700 transition-all shadow-sm shadow-indigo-200">
              + Record Giving <ChevronRight className="w-4 h-4" />
            </Link>
            <Link href="/attendance"
              className="flex items-center gap-2 border border-gray-200 text-gray-600
                         px-5 py-2.5 rounded-xl text-sm font-medium hover:bg-gray-50 transition-colors">
              <CalendarCheck className="w-4 h-4" /> View Attendance
            </Link>
            <button onClick={printStatement}
              className="flex items-center gap-2 border border-indigo-200 text-indigo-600
                         px-5 py-2.5 rounded-xl text-sm font-medium hover:bg-indigo-50 transition-colors">
              <Download className="w-4 h-4" /> Download Statement
            </button>
          </div>

        </div>
      </main>
    </div>
  );
}
